# Dockerfile.worker
FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m spacy download en_core_web_trf
RUN python -c "import nltk; nltk.download('punkt')"

COPY . .

# Override the default command for Celery worker
CMD ["celery", "-A", "tasks.celery_worker.celery_app", "worker", "--loglevel=info", "--pool=solo"]