# render.yaml (Corrected - Disk defined within services)

# This blueprint defines all the services needed for the contract intelligence app.
# 1. A managed Redis instance for Celery.
# 2. A Dockerized web service for the FastAPI API.
# 3. A Dockerized background worker for the Celery process.
# A persistent disk will be created and attached to both the API and Worker.

services:
  # -----------------
  #  1. Redis Service
  # -----------------
  - type: redis
    name: redis-broker
    plan: free

  # -----------------
  #  2. FastAPI Web Service (the API)
  # -----------------
  - type: web
    name: contract-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: contract-app-env
    # --- THIS IS THE CORRECTED SECTION ---
    # Define the persistent disk directly here.
    # It will be created and attached to this service.

    

  # -----------------
  #  3. Celery Background Worker
  # -----------------
  - type: worker
    name: contract-worker
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: celery -A tasks.celery_worker worker --loglevel=info --pool=solo
    envVars:
      - fromGroup: contract-app-env
    # --- THIS IS THE CORRECTED SECTION ---
    # Attach the SAME persistent disk by using the same 'name'.
    # Render is smart enough to know this means they share the volume.


# --- Environment Group Definition ---
envVarGroups:
  - name: contract-app-env```

