services:
  # FastAPI API Service
  - type: web
    name: contract-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: contract_db
      - key: REDIS_URI
        fromService:
          type: redis
          name: contract-redis
          property: connectionString
    healthCheckPath: /docs

  # Celery Worker Service
  - type: worker
    name: contract-worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: celery -A tasks.celery_worker.celery_app worker --loglevel=info --pool=solo
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: contract_db
      - key: REDIS_URI
        fromService:
          type: redis
          name: contract-redis
          property: connectionString

databases:
  - name: contract-redis
    plan: free
