services:
  # FastAPI API Service (with built-in Celery worker)
  - type: web
    name: contract-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: Contract-analysis
      - key: REDIS_URI
        fromService:
          type: redis
          name: contract-redis
          property: connectionString
    healthCheckPath: /docs

  # Managed Redis Service
  - type: redis
    name: contract-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
