# render.yaml

services:
  # -----------------
  #  1. Redis Service
  # -----------------
  - type: redis
    name: redis-broker
    plan: free

  # -----------------
  #  2. FastAPI Web Service (the API)
  # -----------------
  - type: web
    name: contract-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: contract-app-env

  # -----------------
  #  3. Celery Background Worker
  # -----------------
  - type: worker
    name: contract-worker
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: celery -A tasks.celery_worker worker --loglevel=info --pool=solo
    envVars:
      - fromGroup: contract-app-env

# --- Environment Group Definition ---
envVarGroups:
  - name: contract-app-env
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://render_user:renderapptest5678@contract-analysis.rkzewtz.mongodb.net/?retryWrites=true&w=majority
      - key: MONGO_DB_NAME
        value: Contract-analysis
      - key: REDIS_URI
        value: redis://red-d2tf6ure5dus73dpohdg:6379
      - key: UPLOADS_DIR
        value: uploads

