# render.yaml (Corrected for Render Free Tier)

services:
  # -----------------
  #  1. Redis Service
  # -----------------
  - type: redis
    name: redis-broker
    plan: free
    # IP Allow List is required for Redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all connections"

  # -----------------
  #  2. FastAPI Web Service (the API)
  # -----------------
  - type: web
    name: contract-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: contract-app-env
    # FIX: Removed the 'disks' section as it is not supported on the free plan.
    # WARNING: File uploads will be ephemeral and will be deleted on restarts/deploys.
    # FIX: Corrected health check syntax to use 'healthCheckPath'.
    healthCheckPath: /

  # -----------------
  #  3. Celery Background Worker
  # -----------------
  - type: worker
    name: contract-worker
    plan: free
    # For a 'type: worker', you do NOT use the 'runtime' key.
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: celery -A tasks.celery_worker worker --loglevel=info --pool=solo
    envVars:
      - fromGroup: contract-app-env
    # FIX: Removed the 'disks' section. The worker will access the same ephemeral
    # filesystem as the API service to read the recently uploaded file.

# --- Environment Group Declaration ---
# This section correctly declares the group managed in the UI.
envVarGroups:
  - name: contract-app-env