# render.yaml (Final Corrected Version)

services:
  # -----------------
  #  1. Redis Service
  # -----------------
  - type: redis
    name: redis-broker
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all connections"

  # -----------------
  #  2. FastAPI Web Service (the API)
  # -----------------
  - type: web
    name: contract-api
    plan: free
    # 'runtime: docker' is CORRECT for a 'type: web' service.
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: contract-app-env
    # 'disks' and 'healthCheck' are properties of the 'web' service.
    disks:
      - name: uploads-disk
        mountPath: /app/uploads
        sizeGB: 1
    healthCheck:
      path: /

  # -----------------
  #  3. Celery Background Worker
  # -----------------
  - type: worker
    name: contract-worker
    plan: free
    # CRITICAL FIX: The 'runtime: docker' key is REMOVED.
    # For a 'type: worker', Render knows to use Docker because 'dockerfilePath' is present.
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: celery -A tasks.celery_worker worker --loglevel=info --pool=solo
    envVars:
      - fromGroup: contract-app-env
    # 'disks' is a valid property of a 'worker' service.
    disks:
      - name: uploads-disk
        mountPath: /app/uploads
        sizeGB: 1

# --- Environment Group Declaration ---
# This section declares that the services above will use a group managed in the UI.
envVarGroups:
  - name: contract-app-env