# render.yaml (Corrected for Indentation)

services:
  # -----------------
  #  1. Redis Service
  # -----------------
  - type: redis
    name: redis-broker
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all connections"

  # -----------------
  #  2. FastAPI Web Service (the API)
  # -----------------
  - type: web
    name: contract-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: contract-app-env
    # --- INDENTATION FIXED ---
    # 'disks' is a property of the 'web' service, so it must be indented.
    disks:
      - name: uploads-disk
        mountPath: /app/uploads
        sizeGB: 1
    # --- INDENTATION FIXED ---
    # 'healthCheck' is also a property of the 'web' service.
    healthCheck:
      path: /

  # -----------------
  #  3. Celery Background Worker
  # -----------------
  - type: worker
    name: contract-worker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: celery -A tasks.celery_worker.celery_app worker --loglevel=info --pool=solo
    envVars:
      - fromGroup: contract-app-env
    # --- INDENTATION FIXED ---
    # 'disks' is a property of the 'worker' service, so it must be indented.
    disks:
      - name: uploads-disk
        mountPath: /app/uploads
        sizeGB: 1

# --- Environment Group Declaration ---
# This block is correct. It only declares the name of the group.
envVarGroups:
  - name: contract-app-env