# render.yaml (Corrected for Render deployment)

services:
  # -----------------
  #  1. Redis Service (FIXED)
  # -----------------
  - type: redis
    name: redis-broker
    plan: free
    # FIX: Added required IP Allow List to permit connections
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all connections"

  # -----------------
  #  2. FastAPI Web Service (the API)
  # -----------------
  - type: web
    name: contract-api
    plan: free
    runtime: docker # 'runtime: docker' is correct for 'type: web'
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      # This correctly links to the Environment Group managed in the UI
      - fromGroup: contract-app-env
    # We still need the disk for uploads
    disks:
      - name: uploads-disk
        mountPath: /app/uploads
        sizeGB: 1
    healthCheck:
      path: /

  # -----------------
  #  3. Celery Background Worker (FIXED)
  # -----------------
  - type: worker
    name: contract-worker
    plan: free
    # FIX: Removed the invalid 'runtime: docker' line.
    # The 'dockerfilePath' is all that's needed to trigger a Docker build.
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: celery -A tasks.celery_worker worker --loglevel=info --pool=solo
    envVars:
      - fromGroup: contract-app-env
    # Attach the same shared disk
    disks:
      - name: uploads-disk
        mountPath: /app/uploads
        sizeGB: 1

# --- Environment Group Declaration (FIXED) ---
# FIX: This block should only declare the NAME of the group.
# The actual keys and values MUST be managed in the Render UI for security.
envVarGroups:
  - name: contract-app-env