services:
  # FastAPI API Service
  - type: web
    name: contract-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: Contract-analysis
      - key: REDIS_URI
        fromService:
          type: redis
          name: contract-redis
          property: connectionString
    healthCheckPath: /docs

  # Celery Worker Service
  - type: worker
    name: contract-worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.worker
    dockerContext: .
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: Contract-analysis
      - key: REDIS_URI
        fromService:
          type: redis
          name: contract-redis
          property: connectionString

# Managed Redis service on Render
services:
  - type: redis
    name: contract-redis
    plan: free
